name: Deploy to OKE

on:
  workflow_run:
    workflows: ["Gateway - Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: OCI_Secrets
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: "${{ vars.OCI_CLI_REGION }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Deploy to OKE
        run: |
          kubectl set image deployment/gateway gateway=${{ secrets.DOCKER_HUB_USERNAME }}/gateway:latest
          kubectl rollout status deployment/gateway
