name: Build and Push Docker Images

on:
  pull_request:
    branches:
      - main
    paths:
      - 'gateway/**'
      - 'pagamentos/**'
  push:
    branches:
      - main
    paths:
      - 'gateway/**'
      - 'pagamentos/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-gateway:
    environment: OCI_Secrets
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'gateway') || contains(github.event.pull_request.title, 'gateway')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Generate version for gateway with semver logic
        id: version
        run: |
          if [ ! -f gateway/VERSION ]; then
            echo "0.1.0" > gateway/VERSION
          fi

          VERSION=$(cat gateway/VERSION)
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          
          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > gateway/VERSION
          echo "VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Commit new version for gateway
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add gateway/VERSION
          git commit -m "Bump gateway version to ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin main --force

      - name: Build and push Docker image for gateway
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/gateway:${{ env.VERSION }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/gateway:latest \
            --push gateway/

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Scan Docker image for vulnerabilities using Snyk
        run: |
          snyk container test ${{ secrets.DOCKER_HUB_USERNAME }}/gateway:${{ env.VERSION }} || true

  build-pagamentos:
    environment: OCI_Secrets
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'pagamentos') || contains(github.event.pull_request.title, 'pagamentos')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Generate version for pagamentos with semver logic
        id: version
        run: |
          if [ ! -f pagamentos/VERSION ]; then
            echo "0.1.0" > pagamentos/VERSION
          fi

          VERSION=$(cat pagamentos/VERSION)
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          
          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > pagamentos/VERSION
          echo "VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Commit new version for pagamentos
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pagamentos/VERSION
          git commit -m "Bump pagamentos version to ${{ env.VERSION }}" || echo "No changes to commit"
          git push origin main --force

      - name: Build and push Docker image for pagamentos
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/pagamentos:${{ env.VERSION }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/pagamentos:latest \
            --push pagamentos/

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Scan Docker image for vulnerabilities using Snyk
        run: |
          snyk container test ${{ secrets.DOCKER_HUB_USERNAME }}/pagamentos:${{ env.VERSION }} || true

  install-kubectl:
    environment: OCI_Secrets
    runs-on: ubuntu-latest
    name: Install Kubectl for OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: "${{ vars.OCI_CLI_REGION }}"

    steps:
      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Run Kubectl
        run: kubectl get nodes -A
