name: Build and Push Docker Image for Pagamentos Application

on:
  pull_request:
    branches:
      - main
    paths:
      - 'pagamentos/**'
  push:
    branches:
      - main
    paths:
      - 'pagamentos/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    environment: OCI_Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Get current version
        id: get_version
        run: |
          # Se o arquivo VERSION não existir, cria com a versão inicial
          if [ ! -f pagamentos/VERSION ]; then
            echo "1" > pagamentos/VERSION
          fi
          # Lê a versão atual e incrementa
          VERSION=$(cat pagamentos/VERSION)
          NEW_VERSION=$((VERSION + 1))
          echo "$NEW_VERSION" > pagamentos/VERSION
          echo "VERSION=v${NEW_VERSION}" >> $GITHUB_ENV

      - name: Commit new version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          g
